### ISSUE TITLE
What does "Error 500" mean?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-testresult-server#109]
## Your Question

After registering a PCR test in the app and waiting for some hours, a Twitter user is now seeing this:
![FDvjs5vXIAAUsVz](https://user-images.githubusercontent.com/67682506/140972204-44b1d3b5-2f1f-4c97-8279-22b036c9a4ad.jpeg)

What does Error 500 mean? Will the user still receive their test result via the CWA?

**Comment by Ein-Tim** [comment]
FYI: Another Twitter user reports the same, Error 500. 

I hope this is no server issue!

**Comment by Ein-Tim** [comment]
And another report: https://twitter.com/charlotterei1/status/1461303338553810949?s=21

Did you investigate this?

**Comment by Ein-Tim** [comment]
And yet another report: https://twitter.com/Conner96173139/status/1461432721922793475?s=20

**Comment by firewiremb** [comment]
I have the same problem right now. This is extremely annoying. Because I need the test result in a few minutes. I should have asked for a hard copy after all.

**Comment by Ein-Tim** [comment]
@firewiremb There is a known issue with test results in the CWA currently. Sorry for any inconvenience caused at the moment.

**Comment by Ein-Tim** [comment]
@firewiremb Please retry now.

**Comment by firewiremb** [comment]
@Ein-Tim  Now I get a different error message. I give up. Thank you for your support.
![Bildschirmfoto 2021-12-06 um 20 34 51](https://user-images.githubusercontent.com/63193396/144911590-df584f66-7c86-47a9-8639-5232ec1efa15.jpeg)

**Comment by Ein-Tim** [comment]
@firewiremb 

Maybe the test was already registered in your app? You can restore it from the recycle bin.

**Comment by Ein-Tim** [comment]
I didn't encounter this error anymore, thus closing.
