### ISSUE TITLE
keine Übermittlung des PCR Testergebnis - bei mehreren Tests

### ISSUE THREAD

**Issue by Ranger2000** [corona-warn-app/cwa-testresult-server#110]
## Describe the bug
keine Übermittlung des PCR Testergebnis obwohl Testergebnisse vorliegen.
Der "Übermittlungs / Schnittstellen"-Fehler liegt bei mindestens zwei PCR-Tests (Ehepaar) vor.

## Expected behaviour
Da das Testergebnis vom Labor nachweislich hochgeladen wurde, muss die Corona-Warn-App das Testergebnis übermitteln und anzeigen. Sonst macht diese Funktion keinen Sinn.

## Steps to reproduce the issue
1. QR Code des PCR-Test erfolgreich eingescannt
2. Geburtsdatum zur Verifizierung eingegeben
3. PCR-Test wurde erfolgreich in der App hinterlegt.
4. Das Labor www.labor-froreich.de hat am selben Tag den Test fertiggestellt und das Ergebnis hochgeladen.
5. Selbst drei Tage später zeigt die App das Ergebnis nicht an, und behautet das kein Testergebnis vorliegt.

## Technical details
ID 68258DD18B56C6D92384 des Fehleranalyseprotokoll
[CWA Log 2021-11-15 20_41_49.281.zip](https://github.com/corona-warn-app/cwa-testresult-server/files/7541378/CWA.Log.2021-11-15.20_41_49.281.zip)

**Comment by Ranger2000** [comment]
Auch 10 Tage später konnte das nachweislich vorliegende PCR Testergebnis nicht übermittelt werden.
Es liegt eindeutig ein technisches Problem vor 🤔

![IMG_20211121_133222](https://user-images.githubusercontent.com/4620349/142762012-2b10a706-4099-4a6e-b47c-bd630ee58215.jpg)

**Comment by ascheibal** [comment]
Hallo @Ranger2000,

Vielen Dank für die detaillierte Schilderung und die Übermittlung der Logdatei.
Die Schritte 1-3 und 5 können wir daran nachvollziehen.
Schritt 4 müssten wir dahingehend prüfen, ob es bei der Übertragung des Labors in die CWA Infrastruktur zu Fehlern gekommen ist, oder ob ein reguläres Testergebnis vorliegt, es aber von der App nicht abgerufen werden kann.
Vereinzelt ist so etwas schon vorgekommen.
Darf ich fragen, ob Sie und Ihr:e Ehepartner:in das gleiche Handymodell / Betriebssystem verwenden?
Weiteres gern per PN, weil wir hier erstmal keinen Fehler von allgemeinem Interesse in der CWA vermuten.

**Comment by Ranger2000** [comment]
PN an Herr Scheibal

**Comment by lovelytux** [comment]
Hallo!
Vlt. stellt sich dieses Problem doch für mehrere dar! 
Ich habe das gleiche Problem mit einer anderen Teststation.

Selbst Tests, die zuvor in der CWA abgerufen werden konnten, deren Testergebnisse werde nicht mehr angezeigt.
Android. Samsung S20. Sicherheitspatchebene vom 1.10.22

Dank für Hilfe im Voraus!

lovelytux
