### ISSUE TITLE
403 Error on all request on production

### ISSUE THREAD

**Issue by jetwes** [corona-warn-app/cwa-testresult-server#119]
## Describe the bug

All requests result in a 403 error since 24.01.2022 13:00h

Expected 204 - ok 

## Additional context
See  https://github.com/corona-warn-app/cwa-quicktest-onboarding/issues/83 
https://github.com/corona-warn-app/cwa-quicktest-onboarding/issues/84

**Comment by jetwes** [comment]
I don't know. But the testresult-server is for quicktests, also, isn't it. I thought the issue should normally placed here.

**Comment by Ein-Tim** [comment]
@jetwes 

I think PCR/RAT is not using the same server but I'm not sure.
It's definitely ok to leave this issue open to until the incident is resolved.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-11006](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11006)
