### ISSUE TITLE
Keine Übermittlung des PCR Testergebnis

### ISSUE THREAD

**Issue by lovelytux** [corona-warn-app/cwa-testresult-server#138]
[gellöst]

Es ist der gleiche Fehler wie hier bereits hier beschrieben: [https://github.com/corona-warn-app/cwa-testresult-server/issues/110](url) nur mit einer anderen Teststation.

Insofern ist die Lösung vlt. doch im Interesse mehrerer. 

Android. Samsung. Sicherheitspatch-Ebene: 1. Oktober 2022

## Possible Fix
[CWA Log 2022-11-06 09_49_11.652.txt](https://github.com/corona-warn-app/cwa-testresult-server/files/9945467/CWA.Log.2022-11-06.09_49_11.652.txt)

## Additional context
Dank für Hilfe im Voraus!

Grüße
lovelytux

**Comment by Ein-Tim** [comment]
@lovelytux

Danke, dass du diesen Issue geöffnet hast!

> Selbst Tests, die zuvor in der CWA abgerufen werden konnten, deren Testergebnisse werde nicht mehr angezeigt.

Verstehe ich deinen Kommentar in #100 richtig, dass du ein Test in der App registriert hattest, dessen Ergebnis sehen konntest & es nun einfach wieder verschwunden ist & "Ergebnis liegt noch nicht vor" angezeigt wird?

**Comment by lovelytux** [comment]
@Ein-Tim 
Danke für die prompte Rückmeldung!

> Verstehe ich deinen Kommentar in https://github.com/corona-warn-app/cwa-testresult-server/pull/100 richtig, dass du ein Test in der App registriert hattest, dessen Ergebnis sehen konntest & es nun einfach wieder verschwunden ist & "Ergebnis liegt noch nicht vor" angezeigt wird?

Antwort: Ja.

Und für den aktuellen Test heute morgen, gilt das Gleiche. Parallel per Mail habe ich das Ergebnis von der Teststation erhalten. Für diesen Test und für die vorgangenen Tests konnten diese erfolgreich hinzugefügt werden, aber das "Testergebnis liegt noch nicht vor" (in der CWA).

**Comment by Ein-Tim** [comment]
>> Verstehe ich deinen Kommentar in #100 richtig, dass du ein Test in der App registriert hattest, dessen Ergebnis sehen konntest & es nun einfach wieder verschwunden ist & "Ergebnis liegt noch nicht vor" angezeigt wird?
> Antwort: Ja.

Das ist sehr komisch. @thomasaugsten magst du dir das einmal anschauen?

> Und für den aktuellen Test heute morgen, gilt das Gleiche. Parallel per Mail habe ich das Ergebnis von der Teststation erhalten. Für diesen Test und für die vorgangenen Tests konnten diese erfolgreich hinzugefügt werden, aber das "Testergebnis liegt noch nicht vor" (in der CWA).

> Seit ca. 10 Tagen werden die Tests nicht mehr aktualisiert.

Das ist ein bekanntes Problem & liegt in den meisten Fällen an den Laboren. Mehr Infos in den FAQ: https://www.coronawarn.app/de/faq/results/#qr_test

**Comment by lovelytux** [comment]
Bis vor ca. 10 Tagen funktionierte es einwandfrei.

Gerade bei meinem weiteren Gerät, Samsung, Android, einer weiteren Person, gleiche Teststation geschaut. Gleicher Fehler

**Comment by Ein-Tim** [comment]
@lovelytux 

> Bis vor ca. 10 Tagen funktionierte es einwandfrei.

> Gerade bei meinem weiteren Gerät, Samsung, Android, einer weiteren Person, gleiche Teststation geschaut. Gleicher Fehler.

Klingt für mich gleich noch viel mehr wie ein Fehler bei der Teststation. Vielleicht kannst du da mal nachfragen?

> Wie sinnvoll ist diese Hilfestellung? Es geht um Schnellstests, die innerhalb von 24 Stunden ablaufen. Dann nützt mir die CWA nix, wenn sich der Support drei Tage alte nicht abgerufene Tests anschaut. Wenn ich etwas falsch verstehe bitte ich um einen Hinweis. Ich soll doch erst einmal drei Tage warten (müssen) bevor ich mich an den Support wenden darf?

Also hier im Issue Titel hast du geschrieben "Keine Übermittlung des PCR Testergebnis", jetzt schreibst du von Schnelltests. Um welche Art von Tests geht es denn nun? Oder sind beide Testarten betroffen? Könntest du das bitte ein wenig ausfüren?

**Comment by lovelytux** [comment]
@Ein-Tim
Entschuldigung. Es sind nur die Schnelltests betroffen.
Die Fa. unterpunkt9.com habe ich angeschrieben. Diese scheint für imnucode.com verantwortlich zu sein.

**Comment by Ein-Tim** [comment]
@lovelytux

Danke! Mal sehen was die antworten!

**Comment by lovelytux** [comment]
imnucode.com hat sich gemeldet und berichtete, dass es mit Zertifikaten Probleme gab, die nun behoben sind.

Eines hat sich jedoch im Wesentlichen geändert. Mit den Zertifikaten die per Mail in der Vergangenheit von imnucode versandt wurden, ist es nicht mehr möglich einen QR-Code für die CWA zu erhalten/zu erzeugen.

Man muss jetzt an der Teststation vorher sagen, dass man auch einen QR-Code für die CWA haben möchte, dann scannt der zu Testende auf dem Gerät der Teststation einen QR-Code, mit dem es dann nun wieder funktioinert. 

Ein herzliches Dankeschön hier für die Hilfe!

Grüße
