### ISSUE TITLE
Hash of GUID should not be case sensitive

### ISSUE THREAD

**Issue by ingowalther0** [corona-warn-app/cwa-testresult-server#67]
When using the hexadecimal hash of a GUID as a key, the TestResultServer should always use upper case or always use lower case. To avoid duplicate entries for the same GUID, and to avoid false negative lookups. I would suggest enforcing it here, and possibly in addition normalizing the case closer to where the request enters the TestResultServer so callers do not need to care.

https://github.com/corona-warn-app/cwa-testresult-server/blob/faad35c44d5c9b6b9ce7ecd2896b412666194baf/src/main/java/app/coronawarn/testresult/model/TestResult.java#L49

**Comment by f11h** [comment]
This has been fixed in the meantime
