### ISSUE TITLE
Add time stamp to test result

### ISSUE THREAD

**Issue by ascheibal** [corona-warn-app/cwa-testresult-server#93]
## Current Implementation

Test representation as hash (Hashed GUID) and test result are send from the quicktest backend when the test result is confirmed.

## Suggested Enhancement

Pass a timestamp from the Quicktest backend when the test result is confirmed. This timestamp can be considered as confirmation time of the test. The test reuslt shall get an additional attribute timestamp, which is the time of generating the QRCode in the quick-test front end (timestamp value in QRCode) at test registration and will be updated with the time of confirmation at the time the test result is given.
### Interface
The existing REST payload shall be enhanced by a key `"sc": number` containing the time of confirmation in UNIX epoch format. This timestamp shall be mapped to the entity `resultDate`

## Expected Benefits

As Antigen Tests give prove for certain activities (shop visits etc) and are valid for a given period of time, the exact time of the proof is crucial.

**Comment by eilers** [comment]
Ich würde das aktuelle Verhalten sogar als Bug werten! Besonders bei der Meldung eines unspezifischen Tests kann der 2. gültige Test länger auf sich warten, da die Person noch einmal ein zweites Mal erscheinen muss. Das kann bei uns sogar am nächsten Tag passieren!
Ich bitte um eine schnelle Lösung!
